# Coffee Coma VPN Configuration
tokens:
  main: "YOUR_MAIN_BOT_TOKEN_HERE"
  admin: "YOUR_ADMIN_BOT_TOKEN_HERE"

admin_id: YOUR_TELEGRAM_ID_HERE

redis:
  host: "localhost"
  port: 6379

vpn:
  dir: "/etc/openvpn/client-configs/"
  server_ip: "YOUR_SLAVE_SERVER_IP"
  default_port: 1194
  price: 100
  
payment:
  yoomoney:
    token: "YOOMONEY_API_TOKEN_HERE"
    wallet: "YOOMONEY_WALLET_NUMBER_HERE"
  
referral:
  trial_days: 7
  bonus_days: 7

notifications:
  days_before_expire: [3, 1]

logging:
  level: "INFO"
  file: "/var/log/coffeecoma.log"